name: Build FreeRDP on Windows with vcpkg

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install CMake and Ninja
      uses: lukka/get-cmake@latest

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        # Cache vcpkg executable and build data to speed up subsequent runs
        doNotCache: false
        # Optionally specify custom vcpkg root directory if needed
        # vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        runVcpkgInstall: true
        vcpkgJsonGlob: '**/vcpkg.json'

    - name: Configure FreeRDP
      run: cmake -B build -S . -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake" -DWITH_OPENH264=ON -DWITH_FFMPEG=ON

    - name: Build FreeRDP
      run: cmake --build build --config Release

    - name: (Optional) Run tests
      run: ctest --test-dir build --output-on-failure -C Release
